# Please use ipxe_inventory.ini
# Usage: ansible-playbook deployment.yaml -i ipxe_inventory.ini
- name: Deploy app, and update envPaths
  hosts: all
  # All vars from ioc_deploy.yml are accessible
  gather_facts: no
  tasks:
  # Assuming you are deploying from dev where you have all the generated ipxe files
  # TODO: But i think want to deploy from artifact storage right?

  # Ansible is idempotent, the copy task will only copy files over if it doesn't exist
  # or if the file contents changed, it does this by comparing the checksum of the src
  # and the dest file, this is also recursivly done if you specify a directory
  # as the src instead of a file
  - name: Deploy changed files
    hosts: all
    tasks:
      - name: Deploy files from the specified folder
        copy:
          src: "{{ generated_ipxe_folder }}/"
          dest: "{{ ipxe_release_folder }}"



