# Please use ipxe_inventory.ini
# Usage: ansible-playbook --extra-vars "source=../build_results/generated_dev_ipxe_files" -i ipxe_inventory.ini -l S3DF ipxe_deployment.yaml

---
- name: Deploy ipxe app
  hosts: all
  gather_facts: no
  vars:
    generated_ipxe_directory: "{{ source }}"

  tasks:
    - name: Get list of files in the source directory
      find:
        paths: "{{ generated_ipxe_directory }}"
        file_type: file
      register: found_files

    - name: Deploy
      ansible.builtin.include_tasks: ipxe_deployment_helper.yaml
      loop: "{{ found_files.files }}"
      loop_control:
        loop_var: file
      no_log: true

# TODO: Not legal - looping over block, instead make a seperate playbook
    # - name: Prompt user for confirmation
    #   pause:
    #     prompt: "Do you want to continue with copying files? (yes/no)"
    #   register: user_confirmation

    # - name: Copy files to destination
    #   copy:
    #     src: "{{ item }}"
    #     dest: "{{ ipxe_release_folder }}"
    #   loop: "{{ found_files.files | map(attribute='path') | list }}"
    #   when: user_confirmation.user_input == 'yes'


