# Please use ipxe_inventory.ini
# Usage: ansible-playbook --extra-vars "source=../build_results/generated_dev_ipxe_files" -i ipxe_inventory.ini -l S3DF ipxe_deployment.yaml

---
- name: Deploy app
  hosts: all
  tasks:
  # Assuming you are deploying from dev where you have all the generated ipxe files
  # TODO: But i think want to deploy from artifact storage right?

  # Ansible is idempotent, the copy task will only copy files over if it doesn't exist
  # or if the file contents changed, it does this by comparing the checksum of the src
  # and the dest file, this is also recursivly done if you specify a directory
  # as the src instead of a file
  - name: 'Deploy files at {{ source }} from the specified folder {{ ipxe_release_folder }}'
    copy:
      src: "{{ source }}/"
      dest: "{{ ipxe_release_folder }}"



